# fly.toml app configuration file generated for strong-type-hono on 2024-12-11T09:31:02+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'strong-type-hono'
primary_region = 'nrt'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
